In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

#Section A

Part 1

Que1.

In [2]:
sales=Series([120,150,180,210])
sales

0    120
1    150
2    180
3    210
dtype: int64

Que2.

In [3]:
marks=Series([72,81,69,90])
marks.values

array([72, 81, 69, 90])

Que3.

In [4]:
marks.index

RangeIndex(start=0, stop=4, step=1)

Que4.

In [5]:
Temp=Series([28,31,30,29],index=['Mon','Tue','Wed','Thu'])
Temp

Mon    28
Tue    31
Wed    30
Thu    29
dtype: int64

Que5.

In [6]:
pop=Series([35,42,31],index=['Delhi','Mumbai','Jaipur'])
pop.values

array([35, 42, 31])

Que6.

In [7]:
score=Series([35,68,44,79,52])
score>50

0    False
1     True
2    False
3     True
4     True
dtype: bool

Que7.

In [8]:
sub=Series([76,83,91],index=['Physics','Chemistry','Maths'])
'Chemistry' in sub

True

Que8.

In [9]:
sub1=sub.to_dict()
sub1

{'Physics': 76, 'Chemistry': 83, 'Maths': 91}

Que9.

In [10]:
prices={'Pen':10,'Notebook':55,'Bag':700}
prices

{'Pen': 10, 'Notebook': 55, 'Bag': 700}

In [11]:
price_Series=Series(prices)
price_Series

Pen          10
Notebook     55
Bag         700
dtype: int64

Que10.

The keys becomes series index

Que11.

In [12]:
data={'A':10,'B':20,'C':30}
s=Series(data,index=['A','B','C','D'])

Que12.

In [13]:
s.isnull()

A    False
B    False
C    False
D     True
dtype: bool

Que13.

In [14]:
s.notnull()

A     True
B     True
C     True
D    False
dtype: bool

Que14.

In [15]:
sales=Series([120,150,180,210],index=['Jan','Feb','Mar','Apr'])
sales

Jan    120
Feb    150
Mar    180
Apr    210
dtype: int64

In [16]:
sales.name='Monthly Sales'
sales

Jan    120
Feb    150
Mar    180
Apr    210
Name: Monthly Sales, dtype: int64

Que15.

In [17]:
sales.index.name='Month'
sales

Month
Jan    120
Feb    150
Mar    180
Apr    210
Name: Monthly Sales, dtype: int64

#Section B

Que16.

In [18]:
s=Series([18,45,27,61],index=['P','Q','R','S'])
s[s>30]

Q    45
S    61
dtype: int64

Que17.

In [19]:
s=Series([500,600,700],index=['East','West','North'])
'West' in s

True

In [20]:
500 in s

False

Que18.

In [21]:
city_data={'Delhi':80,'Pune':65,'Kochi':70}

In [22]:
city_new_data=Series(city_data,index=['Delhi','Pune','Kochi','Chennai'])
city_new_data

Delhi      80.0
Pune       65.0
Kochi      70.0
Chennai     NaN
dtype: float64

Que19.

In [23]:
s=Series({'W':5,'X':10,'Y':15},index=['W','X','Y','Z'])

In [24]:
pd.isnull(s)

W    False
X    False
Y    False
Z     True
dtype: bool

Que20.

In [25]:
pd.notnull(s)

W     True
X     True
Y     True
Z    False
dtype: bool

Que21.

In [26]:
s1=Series([10,20,30],index=['A','B','C'])

In [27]:
s2=Series([1,2,3],index=['C','A','B'])

In [28]:
s1+s2

A    12
B    23
C    31
dtype: int64

Que22.

In [29]:
s1=Series({'A':10,'B':20})

In [30]:
s2=Series({'B':5,'C':9})

In [31]:
s1+s2

A     NaN
B    25.0
C     NaN
dtype: float64

Que23.

In [32]:
stock=Series([25,40,18],index=['item1','item2','item3'])

In [33]:
stock_dict=stock.to_dict()
stock_dict

{'item1': 25, 'item2': 40, 'item3': 18}

In [34]:
Stock=Series(stock_dict)
Stock

item1    25
item2    40
item3    18
dtype: int64

Que24.

In [35]:
marks={'Maths':88,'Science':74,'English':69,'History':81}

In [36]:
marks_Ser=Series(marks)
marks_Ser

Maths      88
Science    74
English    69
History    81
dtype: int64

In [37]:
marks_Ser[marks_Ser>70]

Maths      88
Science    74
History    81
dtype: int64

Que25.

In [38]:
Rev=Series([1,2,3],index=['a','b','c'],name='branch')
Rev

a    1
b    2
c    3
Name: branch, dtype: int64

In [39]:
Rev.name='Revenue'
Rev.index.name='Branch'

#Section C

Que26.

In [40]:
north=Series({'Jan':40,'Feb':55,'March':60})

In [41]:
south=Series({'Feb':20,'March':25,'Apr':30})

In [42]:
north+south

Apr       NaN
Feb      75.0
Jan       NaN
March    85.0
dtype: float64

In pandas index aligns the indexes which are the same otherwise if there is no such index found then it returns the NaN

Que27.

In [43]:
d={'Red':12,'Blue':18,'Green':24}

In [44]:
labels=['Green','Red','Yellow','Blue']

In [45]:
result=Series(d,index=labels)
pd.isnull(result)

Green     False
Red       False
Yellow     True
Blue      False
dtype: bool

(a) Yellow
(b) Returns True For yellow And False for Others
(c) Because it does not have any value just have index name
(d) Red,Blue,Green

Que28.

In [46]:
s=Series([90,75,82],index=['Ravi','Aman','Neha'])
s

Ravi    90
Aman    75
Neha    82
dtype: int64

In [47]:
d=s.to_dict()
d

{'Ravi': 90, 'Aman': 75, 'Neha': 82}

In [48]:
s2=Series(d)
s2

Ravi    90
Aman    75
Neha    82
dtype: int64

Que29.

In [49]:
a=Series([125,323,231,521],index=['A','B','C','D'])

In [50]:
a.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [51]:
a.values

array([125, 323, 231, 521])

In [52]:
a[a>500]

D    521
dtype: int64

In [53]:
pd.notnull(a)

A    True
B    True
C    True
D    True
dtype: bool

In [54]:
a.to_dict()

{'A': 125, 'B': 323, 'C': 231, 'D': 521}

Que30.

In [55]:
data={'A':15,'B':35,'C':25}

In [56]:
a=Series(data,index=['C','A','B','D'])

In [57]:
a.name='Observations'

In [58]:
a.index.name='Category'

In [59]:
#(a)
a.index

Index(['C', 'A', 'B', 'D'], dtype='object', name='Category')

In [60]:
#(b)
a.isnull()
#d is NaN

Category
C    False
A    False
B    False
D     True
Name: Observations, dtype: bool

In [61]:
#(c)
a[a>20].notnull()

Category
C    True
B    True
Name: Observations, dtype: bool

In [62]:
#(d)
a.notnull()

Category
C     True
A     True
B     True
D    False
Name: Observations, dtype: bool

In [63]:
#(e)
a.name

'Observations'

In [64]:
a.index.name

'Category'